name: Deploy

on:
  push:
    branches:
      - main
permissions: 
  id-token: write 
  contents: read
defaults:
  run:
    working-directory: web
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - uses: pnpm/action-setup@v4
          name: Install pnpm
          with:jobs:
            build:
              name: Build
              runs-on: ubuntu-latest
              steps:
                  - name: Checkout
                    uses: actions/checkout@v4
                    with:
                      fetch-depth: 0 # Fetch all history for all branches and tags
          
                  - uses: pnpm/action-setup@v4
                    name: Install pnpm
                    with:
                      version: 9
                      run_install: false
          
                  - name: Install dependencies
                    run: pnpm install
                    working-directory: ./web
          
                  - name: Build project
                    run: npm run build
                    working-directory: ./web
          
                  - name: Deploy 🚀
                    uses: JamesIves/github-pages-deploy-action@v4
                    with:
                      folder: ./web/dist # The folder the action should deploy.
            version: 9
            run_install: false
  
  
        - name: Install dependencies
          run: pnpm install
          working-directory: ./web
        - name: Build project
          run: npm run build
          working-directory: ./web
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ./web/dist # The folder the action should deploy.
       