name: Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: web
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - uses: pnpm/action-setup@v4
          name: Install pnpm
          with:
            version: 9
            run_install: false
  
  
        - name: Install dependencies
          run: pnpm install
          working-directory: ./web
        - name: Build project
          run: npm run build
          working-directory: ./web

        - name: Upload production-ready build files
          uses: actions/upload-artifact@v3
          with:
            name: production-files
            path: ./web/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions: 
      id-token: write 
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
